mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path("", views.index),
    path('admin/', admin.site.urls),
	path('todo/', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
	path("", views.index, name="index"),
	path("add/", views.add_todo, name="add"),
	path('<int:todo_id>/done/', views.done_todo, name='done'),
]

todo/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Todo(models.Model):
	"""Todo is a task with a description and flag to indicate if it is done"""
	# Require the description to be at least 3 chars
	description = models.CharField('Description', max_length=80, blank=False,
					validators=[MinLengthValidator(3)] )
	done = models.BooleanField('Done?', default=False, blank=True)

	def __str__(self):
		return self.description

todo/forms.py
import datetime
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    """Form for inputing a new todo item.
    The done field is not shown, since it's useless to add a todo that
    is already done.
    """    
    class Meta:
        model = Todo
        fields = ['description'] # don't show 'done' field on form for a new todo
        # this doesn't work
        hidden = ['id']
        # custom labels for input fields
        labels = {
            'description': "Description of todo",
            'done': "Is it Done?",
        }

    
    def clean_description(self):
        """Verify the description has required minimum length"""
        description = self.cleaned_data['description']
        if len(description.strip()) < 3:
            raise forms.ValidationError("Description should be at least 3 chars")
        # returned value replaces cleaned data
        return description

mysite/views.py
from django.shortcuts import redirect

def index(request):
    """redirect to todo app"""
    return redirect( 'todo:index' )

todo/views.py
from django.http import HttpResponse, HttpResponseNotFound
# Model.DoesNotExist is subclass of ObjectDoesNotExist
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import  reverse
from django.views import generic
from todo.models import Todo
from todo.forms import TodoForm

# function-based views
def index(request):
	"""Return a list of current todo tasks with a form for adding a new todo"""
	todo_list = Todo.objects.filter(done=False)
	form = TodoForm()
	context = {'form': form, 'todo_list': todo_list}
	return render(request, 'todo/todo_list.html', context)

def add_todo(request):
	"""Add a new todo. Should be invoked via POST method."""
	if request.method == 'POST':
		form = TodoForm(request.POST)
		if form.is_valid():
			# should log the action
			form.save()
			messages.success(request, 
				f"Added \"{request.POST['description']}\"" )
			return redirect('todo:index')
	else:  # GET /add/ should be handled by the main index
		return redirect('todo:index')
	return render(request, 'todo/add.html', {'form': form})


def done_todo(request, todo_id: int):
	"""Mark a todo as done, then redirect back to the index page."""
	try:
		todo = Todo.objects.get(id=todo_id)
	except ObjectDoesNotExist:
		return HttpResponseNotFound(f"<h2>Todo number {todo_id} not found</h2>")
	except Exception as e:
		# treat anything else as server-side error
		return HttpResponse(f"<h2>Error - {str(e)}</h2>", status=500)
	todo.done = True
	todo.save()
	messages.success(request, f"Todo {todo.id} marked as done")
	return redirect('todo:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Todo List</title>{% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">   
  <!-- Additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    th, td { padding: 5px; 
		padding-left: 0.5em;
		padding-right: 0.5em;
    }
  </style>
</head>
<body>

<div class="container-fluid">

<div class="col-sm-10 ">
  {% block content %} {% endblock %}
</div>

</div>
</body>
</html>

todo/templates/todo/add.html
{% extends 'base.html' %}
{% block content %}
<!-- enter data for a new todo record -->
<h3>Create New Todo</h3>

<form action="{% url 'todo:add' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value='Save Todo' />
    &nbsp;&nbsp;
    <button type="reset">Reset</button>
    &nbsp;&nbsp;
    <a href="{% url 'todo:index' %}">Cancel</a>
</form>
{% endblock %}

todo/templates/todo/edit.html
{% extends 'base.html' %}

{% block content %}
<form action="" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value='Update' />
    <a href="{% url 'todo:index' %}">Cancel</a>
</form>
{% endblock %}

todo/templates/todo/todo_list.html
<!-- template for generic.ListView with model=Todo -->
{% extends 'base.html' %}

{% block content %}
<h3>Current Todo Items</h3>

<p>Click the "Done" link when an item is done.</p>

<table border='1'>
<tr><th width="80%">Description</th> <th>Done?</th></tr>
{% for todo in todo_list %}
<tr><td valign="top">
{{todo.description}}
</td>
<td valign="top">
<a href="{% url 'todo:done' todo.id %}">Done</a>
</td>
</tr>
{% empty %}
<tr><td>Nothing to do</td><td>&nbsp;</td></tr>
{% endfor %}
</table>
<!-- Django Messages Framework -->
{% if messages %}
  {% for msg in messages %}
  <p class="{{msg.tags}}">{{ msg }}</p>
  {% endfor %}
{% endif %}

<hr/>
<h3>Add a Todo</h3>

<!--
<div id="add_todo" style="border:1px solid black;">
 -->
<form action="{% url 'todo:add' %}" method='post'>
    {% csrf_token %}

	{{ form.as_p }}
	<input type="submit" value='Save Todo' />
	&nbsp;&nbsp;
	<button type="reset">Clear</button>
</form>

{% endblock %}